# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJ2VTMcuFFeKR0qFTuNxCwQYcWKQ5CIp

# Customer Segmentation - Exploratory Data Analysis (EDA)

**Objective:** Analyze customer data to understand purchasing behavior, demographics, and campaign responses — ultimately to prepare the data for customer segmentation using clustering.

**Dataset:** `marketing_campaign.xlsx` — 2240 customers with 29 features covering People, Products, Promotion, and Place.

---

## Step 1: Load & Explore Data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 12

df = pd.read_excel('marketing_campaign.xlsx')
print(f'Dataset Shape: {df.shape[0]} rows x {df.shape[1]} columns')
df.head()

df.info()

# Column names grouped by category for reference
people_cols = ['Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'Recency']
product_cols = ['MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds']
promo_cols = ['NumDealsPurchases', 'AcceptedCmp1', 'AcceptedCmp2', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'Response']
place_cols = ['NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth']

print(f'People columns   ({len(people_cols)}): {people_cols}')
print(f'Product columns  ({len(product_cols)}): {product_cols}')
print(f'Promotion columns({len(promo_cols)}): {promo_cols}')
print(f'Place columns    ({len(place_cols)}): {place_cols}')
print(f'Other columns: ID, Complain, Z_CostContact, Z_Revenue')

"""## Step 2: Data Quality Checks"""

# Check for missing values
missing_count = df.isnull().sum()
missing_count = missing_count[missing_count > 0]

missing_pct = (missing_count / len(df) * 100).round(2)

missing_df = pd.DataFrame({
    "Missing_Count": missing_count.values,
    "Missing_Percentage": missing_pct.values
})

if not missing_df.empty:
    print(missing_df)
else:
    print("No missing values found!")

# Fill missing Income values with the median
print(f'count of missing Income values: {df["Income"].isnull().sum()} out of {len(df)}')
df['Income'] = df['Income'].fillna(df['Income'].median())
print(f'After filling: {df["Income"].isnull().sum()} missing values')

# Check for duplicates
duplicates = df.duplicated().sum()
print(f'Number of duplicate rows: {duplicates}')
print(f'Unique IDs: {df["ID"].nunique()} out of {len(df)} rows')

"""## Step 3: Feature Engineering

Creating derived features to capture customer value, engagement, household structure, and loyalty.

| Feature | Calculation | Purpose |
|---|---|---|
| `Age` | Current year - Year_Birth | Customer demographic |
| `Total_Spend` | Sum of all 6 product columns | Overall customer value |
| `Total_Purchases` | Web + Catalog + Store | Purchase frequency (excludes Deals) |
| `Total_Dependents` | Kidhome + Teenhome | Household size |
| `Is_Parent` | 1 if Total_Dependents > 0 | Binary parent flag |
| `Total_Campaigns_Accepted` | Sum of AcceptedCmp1-5 | Campaign responsiveness (excludes Response) |
| `Customer_Tenure_Days` | Today - Dt_Customer | Loyalty duration |
"""

# Calculate customer's age using the current year
from datetime import datetime
df['Age'] = datetime.now().year - df['Year_Birth']

# Total spending across all product categories
df['Total_Spend'] = df[['MntWines', 'MntFruits', 'MntMeatProducts',
                         'MntFishProducts', 'MntSweetProducts', 'MntGoldProds']].sum(axis=1)

# Total number of purchases across channels (Web + Catalog + Store only)
# Note: NumDealsPurchases counts discount-based purchases, not a separate channel
df['Total_Purchases'] = df[['NumWebPurchases', 'NumCatalogPurchases',
                            'NumStorePurchases']].sum(axis=1)

# Total dependents (kids + teens)
df['Total_Dependents'] = df['Kidhome'] + df['Teenhome']

# Binary flag: Is the customer a parent?
df['Is_Parent'] = (df['Total_Dependents'] > 0).astype(int)

# Total campaigns accepted (Campaigns 1-5 only, Response kept separate)
df['Total_Campaigns_Accepted'] = df[['AcceptedCmp1', 'AcceptedCmp2', 'AcceptedCmp3',
                                     'AcceptedCmp4', 'AcceptedCmp5']].sum(axis=1)

# Customer tenure in days (from enrollment date to today)
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], format='%d-%m-%Y')
df['Customer_Tenure_Days'] = (pd.to_datetime('today') - df['Dt_Customer']).dt.days

print('New features created:')
print(df[['Age', 'Total_Spend', 'Total_Purchases', 'Total_Dependents',
          'Is_Parent', 'Total_Campaigns_Accepted', 'Customer_Tenure_Days']].describe().round(2))

"""## Step 4: Data Cleaning

Covers descriptive statistics, outlier detection & removal, and categorical variable grouping.

### 4a. Descriptive Statistics
"""

df.describe().T.round(2)

cat_cols = ['Education', 'Marital_Status']

for col in cat_cols:
    print(f'\n--- {col} ---')
    counts = df[col].value_counts()
    pcts = df[col].value_counts(normalize=True).mul(100).round(1)
    print(pd.DataFrame({'Count': counts, 'Percentage': pcts}))

"""### 4b. Outlier Detection & Removal

We target 5 columns: `Income` (data entry error of 666,666), `Age` (impossible values >130), `Total_Spend` (key clustering variable), `MntWines` (~50% of revenue, highest spread), and `MntMeatProducts` (~25% of revenue, max 1,725 vs median 67). Other columns have naturally bounded ranges and don't need treatment.
"""

outlier_cols = ['Income', 'Age', 'Total_Spend', 'MntWines', 'MntMeatProducts']

fig, axes = plt.subplots(1, len(outlier_cols), figsize=(18, 5))
for i, col in enumerate(outlier_cols):
    sns.boxplot(y=df[col], ax=axes[i], color='steelblue')
    axes[i].set_title(col)
plt.suptitle('Boxplots - Outlier Detection', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# Check extreme outliers in Income and Age
print('Income outliers (> $200,000):')
print(df[df['Income'] > 200000][['ID', 'Income', 'Age', 'Total_Spend']].to_string())

print(f'\nAge outliers (> 100 years):')
print(df[df['Age'] > 100][['ID', 'Year_Birth', 'Age']].to_string())

# Remove extreme outliers (Income > 200K and Age > 100)
print(f'\nRows before removing outliers: {len(df)}')
df = df[(df['Income'] < 200000) & (df['Age'] < 100)]
print(f'Rows after removing outliers:  {len(df)}')

# Before/after boxplots for Age and Income
outlier_cols = ['Age', 'Income']

fig, axes = plt.subplots(1, len(outlier_cols), figsize=(10,5))

for i, col in enumerate(outlier_cols):
    sns.boxplot(y=df[col], ax=axes[i])
    axes[i].set_title(col)

plt.suptitle('Outlier Detection: Age vs Income')
plt.tight_layout()
plt.show()

"""### 4c. Clean Categorical Variables

- **Marital Status:** Married/Together → "Partnered"; Single/Divorced/Widow/Alone/Absurd/YOLO → "Single"
- **Education:** Basic/2n Cycle → "Undergraduate"; Graduation → "Graduate"; Master/PhD → "Postgraduate"
"""

# Simplify Marital Status into two groups
df['Marital_Status'] = df['Marital_Status'].replace({
    'Married': 'Partnered', 'Together': 'Partnered',
    'Single': 'Single', 'Divorced': 'Single', 'Widow': 'Single',
    'Alone': 'Single', 'Absurd': 'Single', 'YOLO': 'Single'
})

# Simplify Education into three tiers
df['Education'] = df['Education'].replace({
    'Basic': 'Undergraduate', '2n Cycle': 'Undergraduate',
    'Graduation': 'Graduate', 'Master': 'Postgraduate', 'PhD': 'Postgraduate'
})

print('Marital Status after cleaning:')
print(df['Marital_Status'].value_counts())
print('\nEducation after cleaning:')
print(df['Education'].value_counts())

"""## Step 5: Univariate Analysis

Studying each variable individually — its shape, spread, and center. We ask: *"What does this single variable look like on its own?"*

### 5a. Numerical Feature Distributions
"""

num_features = ['Age', 'Income', 'Recency', 'Total_Spend', 'Total_Purchases', 'Customer_Tenure_Days']

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
axes = axes.flatten()

for i, col in enumerate(num_features):
    sns.histplot(df[col], kde=True, ax=axes[i], color='steelblue', edgecolor='black')
    axes[i].axvline(df[col].mean(), color='red', linestyle='--', label=f'Mean: {df[col].mean():.0f}')
    axes[i].axvline(df[col].median(), color='green', linestyle='--', label=f'Median: {df[col].median():.0f}')
    axes[i].set_title(f'Distribution of {col}')
    axes[i].legend(fontsize=9)

plt.suptitle('Univariate Analysis - Numerical Features', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

"""**Key findings:** Age is roughly symmetric (45-75 range). Income is right-skewed (median ~$51K). Total_Spend is strongly right-skewed — majority below $500 but a long tail to $2,500+. Recency and Customer_Tenure_Days are nearly uniform. Total_Spend and Income will be the strongest differentiators for clustering.

### 5b. Product Spending Distributions
"""

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
axes = axes.flatten()
colors = ['#e74c3c', '#2ecc71', '#e67e22', '#3498db', '#9b59b6', '#f1c40f']

for i, col in enumerate(product_cols):
    sns.histplot(df[col], kde=True, ax=axes[i], color=colors[i], edgecolor='black')
    axes[i].set_title(f'Distribution of {col}')

plt.suptitle('Spending Distribution by Product Category', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

"""### 5c. Product Spending Breakdown"""

# Total and average spending by category
product_spending = df[product_cols].sum().sort_values(ascending=False)
product_labels = ['Wines', 'Meat', 'Gold', 'Fish', 'Sweets', 'Fruits']

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

product_spending.plot(kind='bar', ax=axes[0], color='steelblue', edgecolor='black')
axes[0].set_title('Total Revenue by Product Category')
axes[0].set_ylabel('Total Amount Spent')
axes[0].set_xticklabels(product_labels, rotation=45)

axes[1].pie(product_spending, labels=product_labels, autopct='%1.1f%%',
            colors=sns.color_palette('Set2'), startangle=90, wedgeprops={'edgecolor': 'black'})
axes[1].set_title('Spending Share by Product Category')

plt.tight_layout()
plt.show()

print('Average spending per customer by product:')
print(df[product_cols].mean().sort_values(ascending=False).round(2))

"""**Key findings:** All product columns are heavily right-skewed. Wine dominates at ~50% of total spending, Meat at ~25%. Together they account for ~75% of revenue. The company is heavily dependent on these two categories.

### 5d. Categorical Feature Distributions
"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

order_edu = df['Education'].value_counts().index
sns.countplot(x='Education', data=df, order=order_edu, ax=axes[0], palette='viridis')
axes[0].set_title('Distribution of Education Level')
for p in axes[0].patches:
    axes[0].annotate(f'{int(p.get_height())}', (p.get_x() + p.get_width()/2., p.get_height()),
                     ha='center', va='bottom', fontsize=10)

order_ms = df['Marital_Status'].value_counts().index
sns.countplot(x='Marital_Status', data=df, order=order_ms, ax=axes[1], palette='magma')
axes[1].set_title('Distribution of Marital Status')
for p in axes[1].patches:
    axes[1].annotate(f'{int(p.get_height())}', (p.get_x() + p.get_width()/2., p.get_height()),
                     ha='center', va='bottom', fontsize=10)

plt.tight_layout()
plt.show()

"""### 5e. Campaign Acceptance Rates"""

campaign_cols = ['AcceptedCmp1', 'AcceptedCmp2', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'Response']
campaign_rates = df[campaign_cols].mean() * 100

fig, ax = plt.subplots(figsize=(10, 5))
bars = campaign_rates.plot(kind='bar', color=['#3498db', '#e74c3c', '#2ecc71', '#f39c12', '#9b59b6', '#1abc9c'],
                           edgecolor='black', ax=ax)
ax.set_title('Campaign Acceptance Rate (%)', fontsize=14, fontweight='bold')
ax.set_ylabel('Acceptance Rate (%)')
ax.set_xticklabels(['Campaign 1', 'Campaign 2', 'Campaign 3', 'Campaign 4', 'Campaign 5', 'Last Campaign'],
                   rotation=45)

for p in ax.patches:
    ax.annotate(f'{p.get_height():.1f}%', (p.get_x() + p.get_width()/2., p.get_height()),
               ha='center', va='bottom', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.show()

"""**Key findings:** Graduates dominate (~50%), ~65% are Partnered. All campaigns have low acceptance rates (1-7%), Campaign 2 was least effective, last campaign had the highest response (~15%).

## Step 6: Bivariate Analysis

Examining relationships between pairs of variables — *"When one changes, does the other change too?"*

### 6a. Income vs Total Spend
"""

fig, ax = plt.subplots(figsize=(10, 6))
scatter = ax.scatter(df['Income'], df['Total_Spend'], c=df['Total_Dependents'],
                     cmap='coolwarm', alpha=0.6, edgecolor='gray', s=40)
plt.colorbar(scatter, label='Total Dependents')
ax.set_xlabel('Income')
ax.set_ylabel('Total Spend')
ax.set_title('Income vs Total Spend (colored by Total Dependents)', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

print(f'Correlation (Income vs Total Spend): {df["Income"].corr(df["Total_Spend"]):.3f}')

"""**Finding:** Strong positive correlation (~0.79). Customers with more dependents (warm colors) cluster at lower spending even at similar income levels.

### 6b. Spending by Education & Marital Status
"""

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

edu_order = ['Undergraduate', 'Graduate', 'Postgraduate']
sns.boxplot(x='Education', y='Total_Spend', data=df, order=edu_order, ax=axes[0,0], palette='Set2')
axes[0,0].set_title('Total Spend by Education')

sns.boxplot(x='Education', y='Income', data=df, order=edu_order, ax=axes[0,1], palette='Set2')
axes[0,1].set_title('Income by Education')

sns.boxplot(x='Marital_Status', y='Total_Spend', data=df, ax=axes[1,0], palette='Pastel1')
axes[1,0].set_title('Total Spend by Marital Status')

sns.boxplot(x='Marital_Status', y='Income', data=df, ax=axes[1,1], palette='Pastel1')
axes[1,1].set_title('Income by Marital Status')

plt.tight_layout()
plt.show()

"""**Finding:** Education has minimal effect on spending despite Postgraduates earning more. Marital status shows broadly similar patterns. Neither is a strong segmentation feature alone — Income is the real driver.

### 6c. Impact of Dependents on Spending
"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.boxplot(x='Total_Dependents', y='Total_Spend', data=df, ax=axes[0], palette='RdYlGn')
axes[0].set_title('Total Spend by Number of Dependents')

sns.boxplot(x='Total_Dependents', y='Income', data=df, ax=axes[1], palette='RdYlGn')
axes[1].set_title('Income by Number of Dependents')

plt.tight_layout()
plt.show()

print('Average spending by number of dependents:')
print(df.groupby('Total_Dependents')['Total_Spend'].agg(['mean', 'median', 'count']).round(2))

"""**Finding:** One of the strongest relationships in the dataset. Customers with 0 dependents spend dramatically more (median ~$1,000+). Both spending and income decrease as dependents increase. Must-include feature for clustering.

### 6d. Purchase Channels
"""

channel_means = df[['NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumDealsPurchases']].mean()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

channel_means.plot(kind='bar', ax=axes[0], color=['#3498db', '#e74c3c', '#2ecc71', '#f39c12'], edgecolor='black')
axes[0].set_title('Average Purchases by Channel')
axes[0].set_xticklabels(['Web', 'Catalog', 'Store', 'Deals'], rotation=0)
axes[0].set_ylabel('Average Number of Purchases')

axes[1].pie(channel_means, labels=['Web', 'Catalog', 'Store', 'Deals'],
            autopct='%1.1f%%', colors=['#3498db', '#e74c3c', '#2ecc71', '#f39c12'],
            startangle=90, wedgeprops={'edgecolor': 'black'})
axes[1].set_title('Purchase Channel Distribution')

plt.tight_layout()
plt.show()

# Compare average spending across purchase channels
channel_cols = ['NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases']

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for col, color, label in zip(channel_cols, ['#3498db', '#e74c3c', '#2ecc71'], ['Web', 'Catalog', 'Store']):
    axes[0].scatter(df[col], df['Total_Spend'], alpha=0.3, s=20, color=color, label=label)
axes[0].set_xlabel('Number of Purchases')
axes[0].set_ylabel('Total Spend')
axes[0].set_title('Purchases vs Total Spend by Channel')
axes[0].legend()

avg_spend_by_channel = {
    'Web': df[df['NumWebPurchases'] > 0]['Total_Spend'].mean(),
    'Catalog': df[df['NumCatalogPurchases'] > 0]['Total_Spend'].mean(),
    'Store': df[df['NumStorePurchases'] > 0]['Total_Spend'].mean(),
    'Deals': df[df['NumDealsPurchases'] > 0]['Total_Spend'].mean()
}

bars = axes[1].bar(avg_spend_by_channel.keys(), avg_spend_by_channel.values(),
                   color=['#3498db', '#e74c3c', '#2ecc71', '#f39c12'], edgecolor='black')
axes[1].set_title('Average Total Spend by Channel Users')
axes[1].set_ylabel('Average Total Spend')
for bar in bars:
    axes[1].text(bar.get_x() + bar.get_width()/2., bar.get_height() + 10,
                 f'${bar.get_height():.0f}', ha='center', fontweight='bold')

plt.tight_layout()
plt.show()

print('Correlation of each channel with Total Spend:')
for col, label in zip(channel_cols + ['NumDealsPurchases'], ['Web', 'Catalog', 'Store', 'Deals']):
    print(f'  {label:10s}: {df[col].corr(df["Total_Spend"]):.3f}')

"""**Finding:** Store is most common, but catalog users have the highest average spending — they are premium buyers. Deal-seekers tend to spend less overall.

### 6e. Demographics & Campaign Deep Dive
"""

# Age groups (temporary — not added to df)
bins = [0, 35, 45, 55, 65, 75, 130]
labels = ['<35', '35-44', '45-54', '55-64', '65-74', '75+']
age_group_temp = pd.cut(df['Age'], bins=bins, labels=labels)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

age_group_temp.value_counts().sort_index().plot(kind='bar', ax=axes[0], color='steelblue', edgecolor='black')
axes[0].set_title('Customer Count by Age Group')
axes[0].set_ylabel('Count')

df.assign(Age_Group_Temp=age_group_temp).groupby('Age_Group_Temp')['Total_Spend'].mean().plot(kind='bar', ax=axes[1], color='coral', edgecolor='black')
axes[1].set_title('Average Spending by Age Group')
axes[1].set_ylabel('Average Total Spend')

plt.tight_layout()
plt.show()

# Income groups (temporary — not added to df)
income_bins = [0, 25000, 50000, 75000, 100000, 200000]
income_labels = ['<25K', '25K-50K', '50K-75K', '75K-100K', '100K+']
income_group_temp = pd.cut(df['Income'], bins=income_bins, labels=income_labels)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

income_group_temp.value_counts().sort_index().plot(kind='bar', ax=axes[0], color='steelblue', edgecolor='black')
axes[0].set_title('Customer Count by Income Group')
axes[0].set_ylabel('Count')

df.assign(Income_Group_Temp=income_group_temp).groupby('Income_Group_Temp')['Total_Spend'].mean().plot(kind='bar', ax=axes[1], color='coral', edgecolor='black')
axes[1].set_title('Average Spending by Income Group')
axes[1].set_ylabel('Average Total Spend')

plt.tight_layout()
plt.show()

# Campaign response analysis
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.boxplot(x='Total_Campaigns_Accepted', y='Total_Spend', data=df, ax=axes[0], palette='YlOrRd')
axes[0].set_title('Total Spend by Campaigns Accepted')

sns.boxplot(x='Total_Campaigns_Accepted', y='Income', data=df, ax=axes[1], palette='YlOrRd')
axes[1].set_title('Income by Campaigns Accepted')

plt.tight_layout()
plt.show()

print('\nCustomer profile by campaign acceptance:')
print(df.groupby('Total_Campaigns_Accepted')[['Income', 'Total_Spend', 'Age', 'Total_Dependents']].mean().round(2))

"""**Finding:** 45-64 age range dominates; spending is consistent across ages. Spending scales linearly with income group. Customers accepting 3-4 campaigns are the highest-value segment — high income, high spend, fewer dependents.

## Step 7: Multivariate Analysis & Pre-Modeling Checks

Looking at three or more variables simultaneously — correlations, feature interactions, skewness, and constant columns.

### 7a. Correlation Heatmap
"""

corr_cols = ['Age', 'Income', 'Recency', 'Total_Spend', 'Total_Purchases', 'Total_Dependents',
             'MntWines', 'MntMeatProducts', 'MntFruits', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds',
             'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumDealsPurchases',
             'NumWebVisitsMonth', 'Total_Campaigns_Accepted', 'Customer_Tenure_Days']

corr_matrix = df[corr_cols].corr()

fig, ax = plt.subplots(figsize=(16, 12))
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, mask=mask, annot=True, fmt='.2f', cmap='RdBu_r', center=0,
            square=True, linewidths=0.5, ax=ax, vmin=-1, vmax=1, annot_kws={'size': 8})
ax.set_title('Correlation Heatmap - Key Features', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""**Key patterns:** Income ↔ Total_Spend (~0.79) strongly positive. Total_Dependents negatively correlated with all spending features. Recency shows near-zero correlation with everything. Income, Total_Dependents, and Total_Spend form a tight cluster — potential redundancy for clustering.

### 7b. Top Correlations with Total Spend
"""

spending_corr = corr_matrix['Total_Spend'].drop('Total_Spend').sort_values(ascending=False)

fig, ax = plt.subplots(figsize=(10, 6))
colors = ['green' if x > 0 else 'red' for x in spending_corr]
spending_corr.plot(kind='barh', color=colors, edgecolor='black', ax=ax)
ax.set_title('Correlation with Total Spend', fontsize=14, fontweight='bold')
ax.set_xlabel('Correlation Coefficient')
ax.axvline(x=0, color='black', linewidth=0.8)
plt.tight_layout()
plt.show()

"""**Finding:** Top positive predictors: MntWines, MntMeatProducts, NumCatalogPurchases, Income. Top negative: Total_Dependents, NumWebVisitsMonth, NumDealsPurchases. Features near zero (Recency, Customer_Tenure_Days) may add noise to clustering.

### 7c. Pairplot
"""

pair_cols = ['Income', 'Total_Spend', 'Age', 'Total_Dependents', 'Recency']

sns.pairplot(df[pair_cols], diag_kind='kde', plot_kws={'alpha': 0.4, 's': 20})
plt.suptitle('Pairplot - Key Features', fontsize=14, fontweight='bold', y=1.02)
plt.show()

"""### 7d. Skewness Check"""

skew_cols = ['Income', 'Total_Spend', 'MntWines', 'MntFruits', 'MntMeatProducts',
             'MntFishProducts', 'MntSweetProducts', 'MntGoldProds', 'Age', 'Recency']

skewness = df[skew_cols].skew().sort_values(ascending=False)

fig, ax = plt.subplots(figsize=(10, 5))
colors = ['red' if abs(x) > 1 else 'orange' if abs(x) > 0.5 else 'green' for x in skewness]
skewness.plot(kind='barh', color=colors, edgecolor='black', ax=ax)
ax.set_title('Skewness of Numerical Features', fontsize=14, fontweight='bold')
ax.set_xlabel('Skewness')
ax.axvline(x=0, color='black', linewidth=0.8)
ax.axvline(x=1, color='red', linewidth=0.8, linestyle='--', label='High skew threshold')
ax.axvline(x=-1, color='red', linewidth=0.8, linestyle='--')
ax.legend()
plt.tight_layout()
plt.show()

print('\nSkewness values:')
for col, val in skewness.items():
    status = 'HIGH' if abs(val) > 1 else 'Moderate' if abs(val) > 0.5 else 'OK'
    print(f'  {col:20s}: {val:+.3f}  ({status})')

"""### 7e. Constant / Low-Variance Columns"""

print('Columns with constant values (zero variance):')
for col in df.select_dtypes(include=np.number).columns:
    if df[col].nunique() <= 1:
        print(f'  {col}: unique value = {df[col].unique()}')
    elif df[col].std() == 0:
        print(f'  {col}: std = 0')

print(f'\nZ_CostContact unique values: {df["Z_CostContact"].unique()}  -->  Constant, can be dropped')
print(f'Z_Revenue unique values:     {df["Z_Revenue"].unique()}  -->  Constant, can be dropped')
print(f'\nComplain value counts:\n{df["Complain"].value_counts()}')

"""**Pre-modeling summary:** Most product columns are highly skewed — StandardScaler will be needed. Z_CostContact and Z_Revenue are constant (drop). Complain has <1% variance (drop). Recency and Customer_Tenure_Days show near-zero correlations with spending (candidates for dropping).

## Step 8: Feature Selection & Summary

Encoding categorical columns, dropping redundant features, and saving the final model-ready dataset.

### 8a. Label Encoding

- **Education** has a natural order: Undergraduate (0) < Graduate (1) < Postgraduate (2)
- **Marital_Status** has 2 values: Partnered (0), Single (1)
"""

# Label Encode categorical columns
education_map = {'Undergraduate': 0, 'Graduate': 1, 'Postgraduate': 2}
df['Education'] = df['Education'].map(education_map)

marital_map = {'Partnered': 0, 'Single': 1}
df['Marital_Status'] = df['Marital_Status'].map(marital_map)

print('Label Encoding applied:')
print(f'  Education     — {education_map}')
print(f'  Marital_Status — {marital_map}')

"""### 8b. Drop Redundant Columns"""

# Drop all redundant, constant, and identifier columns
columns_to_drop = [
    'ID',                    # Unique identifier — not a feature
    'Year_Birth',            # Redundant — replaced by Age
    'Dt_Customer',           # Datetime — replaced by Customer_Tenure_Days
    'Kidhome',               # Redundant — replaced by Total_Dependents
    'Teenhome',              # Redundant — replaced by Total_Dependents
    'Z_CostContact',         # Constant (always 3)
    'Z_Revenue',             # Constant (always 11)
    'Complain',              # Very low variance (<1% complained)
    'Is_Parent',             # Redundant — derived from Total_Dependents
    'Customer_Tenure_Days',  # Low correlation with all features in EDA
    'AcceptedCmp1', 'AcceptedCmp2', 'AcceptedCmp3',  # Redundant — replaced by
    'AcceptedCmp4', 'AcceptedCmp5',                   # Total_Campaigns_Accepted
    'MntWines', 'MntFruits', 'MntMeatProducts',       # Redundant — replaced by
    'MntFishProducts', 'MntSweetProducts', 'MntGoldProds',  # Total_Spend
    'NumWebPurchases', 'NumCatalogPurchases',          # Redundant — replaced by
    'NumStorePurchases',                               # Total_Purchases
]

df_model = df.drop(columns=columns_to_drop)

print(f'Columns dropped: {len(columns_to_drop)}')
print(f'Final feature set: {df_model.shape[1]} columns x {df_model.shape[0]} rows')
print(f'\nFeatures for clustering:')
print(df_model.columns.tolist())

# Quick look at the final modeling-ready dataset
print('Final Dataset Summary:')
print(df_model.describe().T.round(2))
print(f'\nData types:')
print(df_model.dtypes)
print(f'\nMissing values: {df_model.isnull().sum().sum()}')
df_model.head(10)

"""### Final Feature Set (12 features)

| Feature | Type | Why Included |
|---|---|---|
| `Income` | Continuous | Primary spending driver (~0.79 correlation) |
| `Recency` | Continuous | Days since last purchase — engagement measure |
| `Age` | Continuous | Customer demographic |
| `Total_Spend` | Continuous | Overall customer value |
| `Total_Purchases` | Continuous | Purchase frequency |
| `Total_Dependents` | Discrete | Strongest behavioral signal |
| `Total_Campaigns_Accepted` | Discrete | Campaign responsiveness |
| `NumDealsPurchases` | Discrete | Deal-seeking behavior |
| `NumWebVisitsMonth` | Discrete | Online engagement |
| `Response` | Binary | Last campaign response |
| `Education` | Encoded (0-2) | Education tier |
| `Marital_Status` | Encoded (0-1) | Partnership status |
"""

# Save the modeling-ready dataset
df_model.to_csv('customer_segmentation_model_ready.csv', index=False)
print("Saved 'customer_segmentation_model_ready.csv' — ready for Model Building!")

"""### EDA Key Findings

**Data Quality:** 24 missing Income values filled with median. 4 extreme outliers removed. 2 constant columns identified. Categoricals cleaned and grouped.

**Customer Profile:** Most customers aged 45-70, majority Graduates, ~65% Partnered, ~72% parents.

**Spending:** Wine + Meat = ~75% of revenue. Income strongly drives spending. Dependents suppress it. Distributions are right-skewed.

**Channels:** Store most common, but catalog users are premium buyers.

**Campaigns:** Low acceptance rates (1-7%). Responders have higher income and spending.

> **Next Step:** `customer_segmentation_model_ready.csv` is ready for **StandardScaler → PCA → K-Means clustering**.
"""